# Generated by Django 3.1.7 on 2021-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=40)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
